### ISSUE TITLE
It recently not working with darmuhsTerminalStuff

### ISSUE THREAD

**Issue by PinipigCrunch01** [kRYstall9/FastSwitchPlayerViewInRadarMOD#10]
Hi, your mod is amazing which lessens a lot of time and effort to switch to players. However recently, it does not work with darmuhsTerminalStuff which is also a great addition for terminals. As a terminal guy, your mod is essential for helping players fast, and with darmuhsTerminalStuff, your mod is so important.  Been disabling darmuhsTerminalStuff, because that's how important your mod is haha. But it will be a great help tho, if it's fixed. 

Note: I do not really know how these codings of mods work. I approach this github, because there might be an easy fix?

Thanks a lot!

**Comment by darmuh** [comment]
this is an issue on my end and i'm going to push out a fix to make this mod and mine compatible 👍

**Comment by darmuh** [comment]
@kRYstall9 fixed this issue. Problem was my commands were modifying the "ViewInsideShipCam 1" object and seemed to be changing it's name to something else. I've updated everything that should to retain that object name 👍

**Comment by kRYstall9** [comment]
@PinipigCrunch01 The fix has been addressed as stated above. @darmuh Thanks for the fix!
