### ISSUE TITLE
Issue + Suggestion

### ISSUE THREAD

**Issue by Bruu404** [kRYstall9/FastSwitchPlayerViewInRadarMOD#2]
Stops working in certain scenarios, for example, when you type a code for a turret or door you have to reopen "view monitor" for the quickswitch to work again.

Could we perhaps just switch players like we do in the monitor and assign that to a custom keybind like mouse5 (which doesn't input anything in the terminal)

**Comment by RainGamma** [comment]
Yeah agree

**Comment by kRYstall9** [comment]
A patch has been released for this suggestion. You find all the news in the readme of this repo
