### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Bruu404** [kRYstall9/FastSwitchPlayerViewInRadarMOD#4]
Might be cuz I have a 60% keyboard, so I need to press FN + WASD

But either way I tried with rightenter and rightctrl, didn't manage to have it work

**Comment by kRYstall9** [comment]
@Bruu404 Have you tried changing the hotkeys inside the configuration file? Just look at the "Acceptable Values" inside the file and choose one of those keys. Just write the key as it is written in the acceptable values section.

You can find the config file associated to my mod in:C:\Users\%user%\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\LethalCompanyModded\BepInEx\config

**Comment by The-Tarkol** [comment]
I'll test on latest version, but when I used v1.0.3 it was not working. Could have been a mod conflict, when I rolled back to 1.0.2 it seemed functional once again. I'll let you know if it is fixed :)

Also the Discord link appears to be broken, it takes me to a server where I have no access to text or voice channels.

**Comment by kRYstall9** [comment]
@The-Tarkol Let me know. And I've updated the README. Now it shows the invite like to the discord. Issue addressed here #5

**Comment by The-Tarkol** [comment]
> @The-Tarkol Let me know. And I've updated the README. Now it shows the invite like to the discord. Issue addressed here #5

Seems to be a bit inconsistent - if I use "Switch X" to swap to another player, the arrow keys will work until it views myself. Then it repeatedly reloads my own perspective. Seems similar to https://github.com/kRYstall9/FastSwitchPlayerViewInRadarMOD/issues/7

Let me know if there's anything else I can offer to assist :)

**Comment by kRYstall9** [comment]
A patch has been released. You can download the new version of the mod [here](https://thunderstore.io/c/lethal-company/p/kRYstall9/FastSwitchPlayerViewInRadar/)
