### ISSUE TITLE
Unable to send the ship back into orbit with this mod installed.

### ISSUE THREAD

**Issue by Clark919** [kRYstall9/FastSwitchPlayerViewInRadarMOD#6]
In the latest version, the lever will always say "wait for ship to land" when you are on a moon. I've had this issue reported to me by players of my [modpack](https://thunderstore.io/c/lethal-company/p/TeamClark/TheMostLethalCompany/), and we've identified this particular mod as the issue. If you scroll down on the modpack page, you'll see a list of everything I'm running with it in the case of an incompatibility. I can also provide logs if needed.

**Comment by kRYstall9** [comment]
@Clark919 could you provide the logs?

**Comment by nikolateslax** [comment]
I'm having the same issue. Here are my logs, in case it helps. Seems like maybe a compatibility problem with BlueAmulet-LCBetterClock
[LogOutput.log](https://github.com/kRYstall9/FastSwitchPlayerViewInRadarMOD/files/13607634/LogOutput.log)

**Comment by kRYstall9** [comment]
A patch has been released. You can download the new version of the mod [here](https://thunderstore.io/c/lethal-company/p/kRYstall9/FastSwitchPlayerViewInRadar/)
