### ISSUE TITLE
glitch where i cant switch to other players besides myself in new vers 

### ISSUE THREAD

**Issue by RainGamma** [kRYstall9/FastSwitchPlayerViewInRadarMOD#7]
In new vers switching to other players is broken, cant switch to others with arrow key in vers 1.1.0

**Comment by kRYstall9** [comment]
@RainGamma are you using the LCDBetterClock mod?

**Comment by RainGamma** [comment]
no im not using that

**Comment by RainGamma** [comment]
![image](https://github.com/kRYstall9/FastSwitchPlayerViewInRadarMOD/assets/44179878/708e069c-70d6-4612-bba7-313ae2d510d8)

**Comment by kRYstall9** [comment]
@RainGamma Do you have any logs? Could you provide them?

**Comment by RainGamma** [comment]
one second

**Comment by RainGamma** [comment]
not sure how to access logs in thunderstore

**Comment by RainGamma** [comment]
![image](https://github.com/kRYstall9/FastSwitchPlayerViewInRadarMOD/assets/44179878/085491d5-6e12-43e1-8621-7b1eb6e7534e)
all i can see on this

**Comment by RainGamma** [comment]
if someone switches to monitor to someone else and i press arrow key it swaps to me

**Comment by kRYstall9** [comment]
If you're not manually installing the mods, then go to: C:\Users\yourUser\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\yourLethalCompanyProfile\BepInEx

**Comment by RainGamma** [comment]
i dont see r2modmanPlus

**Comment by RainGamma** [comment]
im just using thunderstore

**Comment by RainGamma** [comment]
[LogOutput.log](https://github.com/kRYstall9/FastSwitchPlayerViewInRadarMOD/files/13608007/LogOutput.log)

**Comment by RainGamma** [comment]
I dont think its any of my mods

**Comment by kRYstall9** [comment]
Working on the problem. As soon as I can I'll release a patch! None of the mods interfered

**Comment by RainGamma** [comment]
Okay thanks

**Comment by kRYstall9** [comment]
A patch has been released. You can download the new version of the mod [here](https://thunderstore.io/c/lethal-company/p/kRYstall9/FastSwitchPlayerViewInRadar/)
