### ISSUE TITLE
[Sugestion] Don't make an all in one mod

### ISSUE THREAD

**Issue by theRealCarneiro** [kRYstall9/FastSwitchPlayerViewInRadarMOD#8]
Would it be possible to consider creating a modpack instead of a single mod that encompasses various functions already covered by existing mods? I currently possess mods that fulfill the majority of the objectives mentioned in the readme, such as door opening and terminal clocks. I've engaged in similar discussions with other members of the community regarding the "more company" mod that accommodates up to 8 players in-game and offers character customization. Personally, it seems more logical to keep these separate rather than bundling them together.
I'm completely open to uninstalling my current mods and installing this one. However, I do prefer keeping functionalities separate and organized.

**Comment by kRYstall9** [comment]
Thanks for the feedback and suggestion. I released a new version of this mod. The mod, as it is right now, just accomplishes its main purpose. No other mod will be integrated in this one from now on
