### ISSUE TITLE
Mod incompatibility

### ISSUE THREAD

**Issue by SpruceWLW** [kRYstall9/FastSwitchPlayerViewInRadarMOD#9]
Hey, this mod is currently incompatible with [24HourClock](https://thunderstore.io/c/lethal-company/p/Zduniusz/24HourClock/)

With both of these mods installed, when you land the ship it will not let you go and you have to wait the entire day to leave.

I've got into contact with the other mod creator and got a temporary fix for now, but they said to get into contact with the creator of this mod if I want a long-term fix.

The other mod creator "zduniusz" has said that this mod expects both AM and PM in the clocks text, and because that part's removed it crashes.

The other mod creators discord is: zduniusz

**Comment by kRYstall9** [comment]
@FreeSpeechMC I'm currently working on it. Soon it'll be patched. Thanks for the feedback

**Comment by kRYstall9** [comment]
A patch has been released. You can download the new version of the mod [here](https://thunderstore.io/c/lethal-company/p/kRYstall9/FastSwitchPlayerViewInRadar/)
